### ISSUE TITLE
0.10 лучше вынести в переменную и дать имя

### ISSUE THREAD

**Issue by coursar** [ayrat-l/wallpapers-calculation#2]
https://github.com/ayrat-l/wallpapers-calculation/blob/2417c090ac71184f61a7e311e7dcdff01a4d1663/lib.py#L16

**Comment by ayrat-l** [comment]
Сделано

**Comment by coursar** [comment]
1. Выполненные issue надо закрывать
1. Нужно закрывать issue сообщения коммитов
